#!/bin/sh
# Runs on the BUILD machine (has Docker + internet/registry access) — never on
# the air-gapped target. Builds the api image, pulls the pinned base images,
# saves all three as .tar files, and (re)populates release/ with everything
# needed for an offline install. The result is what gets copied to USB/DVD.
#
# Usage: sh scripts/build_release.sh [version]
#   version defaults to API_IMAGE_TAG in .env, or 1.0.0 if unset.
set -eu

REPO_ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$REPO_ROOT"

log()  { printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$1"; }
fail() { printf '\nERROR: %s\n' "$1" >&2; exit 1; }

command -v docker >/dev/null 2>&1 || fail "docker not found on PATH."
docker info >/dev/null 2>&1 || fail "docker is installed but the daemon is not reachable."

API_IMAGE_NAME="hospital-directory-api"
POSTGRES_IMAGE="postgres:16-alpine"
PGADMIN_IMAGE="dpage/pgadmin4:latest"

VERSION="${1:-}"
if [ -z "$VERSION" ] && [ -f .env ]; then
    VERSION="$(grep '^API_IMAGE_TAG=' .env 2>/dev/null | cut -d= -f2 || true)"
fi
VERSION="${VERSION:-1.0.0}"

API_IMAGE="${API_IMAGE_NAME}:${VERSION}"

RELEASE_DIR="$REPO_ROOT/release"
IMAGES_DIR="$RELEASE_DIR/docker-images"
DATABASE_DIR="$RELEASE_DIR/database"
COMPOSE_DIR="$RELEASE_DIR/compose"
DOCS_DIR="$RELEASE_DIR/documentation"
CHECKSUMS_DIR="$RELEASE_DIR/checksums"

log "Building release $VERSION"

mkdir -p "$IMAGES_DIR" "$DATABASE_DIR" "$COMPOSE_DIR" "$DOCS_DIR" "$CHECKSUMS_DIR"

log "Step 1/6: Building the API image ($API_IMAGE) ..."
docker build -t "$API_IMAGE" .

log "Step 2/6: Pulling pinned base images ($POSTGRES_IMAGE, $PGADMIN_IMAGE) ..."
docker pull "$POSTGRES_IMAGE"
docker pull "$PGADMIN_IMAGE"

log "Step 3/6: Saving images to $IMAGES_DIR ..."
rm -f "$IMAGES_DIR"/*.tar
docker save -o "$IMAGES_DIR/api.tar" "$API_IMAGE"
docker save -o "$IMAGES_DIR/postgres.tar" "$POSTGRES_IMAGE"
docker save -o "$IMAGES_DIR/pgadmin.tar" "$PGADMIN_IMAGE"

log "Step 4/6: Syncing database validation/rollback/migration docs into release/database ..."
mkdir -p "$DATABASE_DIR/validation" "$DATABASE_DIR/rollback" "$DATABASE_DIR/migrations"
cp -f database/postgres/validation/*.sql "$DATABASE_DIR/validation/"
cp -f database/postgres/rollback/rollback_notes.md "$DATABASE_DIR/rollback/"
cp -f database/postgres/migrations/README.md "$DATABASE_DIR/migrations/"
cp -f database/postgres/DATABASE_STRUCTURE_REPORT.md "$DATABASE_DIR/"

log "Step 5/6: Regenerating RELEASE_NOTES.md with this build's metadata ..."
BUILD_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
GIT_COMMIT="$(git rev-parse --short HEAD 2>/dev/null || echo 'not a git repository')"
API_DIGEST="$(docker image inspect "$API_IMAGE" --format '{{index .RepoDigests 0}}' 2>/dev/null || echo 'local build, no registry digest')"

cat > "$DOCS_DIR/RELEASE_NOTES.md" <<EOF
# Release Notes

> Regenerated by scripts/build_release.sh at build time — reflects the
> package actually on this DVD, not a stale hand-edited copy.

## Build metadata

| Field | Value |
|---|---|
| Version | $VERSION |
| Built (UTC) | $BUILD_DATE |
| Git commit | $GIT_COMMIT |
| API image | $API_IMAGE |
| API image digest | $API_DIGEST |
| PostgreSQL image | $POSTGRES_IMAGE |
| pgAdmin image | $PGADMIN_IMAGE |

## Component

- **Component**: Hospital Directory Read API — Mock implementation
- **Contract**: \`Hospital_Directory_API_OpenAPI.yaml\` v1.0.0, base path
  \`/api/directory/v1\`
- **Stack**: FastAPI + SQLAlchemy + Alembic, PostgreSQL 16, pgAdmin 4

### What's included

- \`patients\`, \`doctors\`, \`workers\`, \`health\` endpoints per the OpenAPI contract.
- API key authentication (\`X-API-Key\`), health endpoint exempt.
- Fictional seed data: ~100 patients (mixed Arabic/English names, some with
  multiple visits, active and completed visits), 50 doctors (multiple
  specialties, active/inactive), 100 workers (multiple departments,
  active/inactive).
- One-shot \`migrate\` service applies Alembic migrations and seeds data before
  \`api\` starts; \`api\` does not run migrations itself.

### Known gaps (see Document 1 section 25 — deferred to the formal contract)

- Exact field lists for patients/doctors/workers reflect Document 3's proposed
  schema; the production data company may need to adjust field availability.
- \`sex\` allowed values are not yet constrained to an enum pending source
  confirmation.
- Production host/port/HTTPS arrangement is not yet known — this package only
  covers the mock API's offline deployment.

### Compatibility note

This mock API and the future production API must expose identical externally
observable behavior (Document 2 section 2.20). Only the data source differs.
HCAT/HCopilot switch between them via configuration only
(\`HOSPITAL_API_BASE_URL\`, \`HOSPITAL_API_KEY\`) — no code changes.
EOF

log "Step 6/6: Writing checksums ..."
(
    cd "$RELEASE_DIR"
    find . -type f ! -path './checksums/*' -print0 \
        | xargs -0 sha256sum \
        > "$CHECKSUMS_DIR/SHA256SUMS.txt"
)

log "Release $VERSION built at $RELEASE_DIR"
log "Contents:"
du -sh "$RELEASE_DIR"/* 2>/dev/null | sed 's/^/  /'
log ""
log "Next: copy the entire 'release/' folder to USB/DVD and follow"
log "release/documentation/INSTALL_OFFLINE.md on the target server."
